
server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'aweperi'
    url: jdbc:postgresql://localhost:2345/fraud
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update